In [15]:
# ===========================================
# Retail & E-Commerce Talent Pool Analysis
# Data Loading
# Author : Rinda Wahyu Lestari
# ===========================================

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
df = pd.read_csv("../data/retail_ecommerce_talent_pool.csv", sep=";")
df.head()

,candidate_id,city,fresh_graduate_status,skills,excel_skill,sql_skill,python_skill,power_bi_skill,looker_studio_skill,database_skill,tableau_skill,other_skills,candidate_goals,platform_source,province,for_job,upskills,networking,switch_career
0,1,Jawa Tengah,Ya,"Python, Tableau",0,0,1,0,0,0,1,NaN,"Cari Kerja, Upskill, Networking",LinkedIn,Jawa Tengah,1,1,1,0
1,2,Padang,Ya,"Excel, SQL, Python, Power BI",1,1,1,1,0,0,0,NaN,"Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Sumatera Barat,1,1,1,1
2,3,Surabaya,Ya,"Excel, SQL, Python, Power BI, Databases",1,1,1,1,0,1,0,NaN,"Cari Kerja, Upskill, Networking",Teman,Jawa Timur,1,1,1,0
3,4,Bandung,Ya,"Python, Power BI",0,0,1,1,0,0,0,NaN,Upskill,LinkedIn,Jawa Barat,0,1,0,0
4,5,Yogyakarta,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...",1,1,1,1,1,1,1,NaN,"Upskill, Networking, Switch Career",Teman,DI Yogyakarta,0,1,1,1

In [10]:
df.head()

,candidate_id,city,fresh_graduate_status,skills,excel_skill,sql_skill,python_skill,power_bi_skill,looker_studio_skill,database_skill,tableau_skill,other_skills,candidate_goals,platform_source,province,for_job,upskills,networking,switch_career
0,1,Jawa Tengah,Ya,"Python, Tableau",0,0,1,0,0,0,1,NaN,"Cari Kerja, Upskill, Networking",LinkedIn,Jawa Tengah,1,1,1,0
1,2,Padang,Ya,"Excel, SQL, Python, Power BI",1,1,1,1,0,0,0,NaN,"Cari Kerja, Upskill, Networking, Switch Career",LinkedIn,Sumatera Barat,1,1,1,1
2,3,Surabaya,Ya,"Excel, SQL, Python, Power BI, Databases",1,1,1,1,0,1,0,NaN,"Cari Kerja, Upskill, Networking",Teman,Jawa Timur,1,1,1,0
3,4,Bandung,Ya,"Python, Power BI",0,0,1,1,0,0,0,NaN,Upskill,LinkedIn,Jawa Barat,0,1,0,0
4,5,Yogyakarta,Tidak,"Excel, SQL, Python, Power BI, Looker Studio, D...",1,1,1,1,1,1,1,NaN,"Upskill, Networking, Switch Career",Teman,DI Yogyakarta,0,1,1,1

In [11]:
df.tail()

,candidate_id,city,fresh_graduate_status,skills,excel_skill,sql_skill,python_skill,power_bi_skill,looker_studio_skill,database_skill,tableau_skill,other_skills,candidate_goals,platform_source,province,for_job,upskills,networking,switch_career
676,677,Jakarta,Ya,"Excel, SQL, Python, Looker Studio",1,1,1,0,1,0,0,NaN,"Upskill, Networking",LinkedIn,Jakarta,0,1,1,0
677,678,Makassar,Tidak,"SQL, Python, Power BI, Databases, Tableau",0,1,1,1,0,1,1,NaN,"Upskill, Networking, Switch Career",LinkedIn,Sulawesi Selatan,0,1,1,1
678,679,Jepara,Tidak,"Excel, SQL, Python, Tableau",1,1,1,0,0,0,1,NaN,Cari Kerja,Teman,Jawa Tengah,1,0,0,0
679,680,Lamongan,Ya,"Databases, Tableau",0,0,0,0,0,1,1,NaN,"Upskill, Networking",Instagram,Jawa Timur,0,1,1,0
680,681,"Bekasi, Jawa Barat",Ya,"Excel, SQL, Python, Power BI, Looker Studio, D...",1,1,1,1,1,1,1,NaN,"Upskill, Networking, Switch Career",LinkedIn,Jawa Barat,0,1,1,1

In [12]:
df.shape

(681, 19)

In [13]:
df.columns

Index(['candidate_id', 'city', 'fresh_graduate_status', 'skills',
       'excel_skill', 'sql_skill', 'python_skill', 'power_bi_skill',
       'looker_studio_skill', 'database_skill', 'tableau_skill',
       'other_skills', 'candidate_goals', 'platform_source', 'province',
       'for_job', 'upskills', 'networking', 'switch_career'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   candidate_id           681 non-null    int64
 1   city                   681 non-null    object
 2   fresh_graduate_status  681 non-null    object
 3   skills                 681 non-null    object
 4   excel_skill            681 non-null    int64
 5   sql_skill              681 non-null    int64
 6   python_skill           681 non-null    int64
 7   power_bi_skill         681 non-null    int64
 8   looker_studio_skill    681 non-null    int64
 9   database_skill         681 non-null    int64
 10  tableau_skill          681 non-null    int64
 11  other_skills           44 non-null     object
 12  candidate_goals        681 non-null    object
 13  platform_source        681 non-null    object
 14  province               681 non-null    object
 15  for_job                681 non-null    int64
 16  upskills               681 non-null    int64
 17  networking             681 non-null    int64
 18  switch_career          681 non-null    int64
dtypes: int64(12), object(7)
memory usage: 101.2+ KB

In [15]:
df.describe()

,candidate_id,excel_skill,sql_skill,python_skill,power_bi_skill,looker_studio_skill,database_skill,tableau_skill,for_job,upskills,networking,switch_career
count,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000,681.000000
mean,341.000000,0.773862,0.823789,0.806167,0.757709,0.588840,0.720999,0.654919,0.660793,0.913363,0.766520,0.400881
std,196.732051,0.418637,0.381280,0.395590,0.428784,0.492406,0.448838,0.475744,0.473788,0.281510,0.423356,0.490437
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,171.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
50%,341.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
75%,511.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,681.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
df.isnull().sum()

candidate_id               0
city                       0
fresh_graduate_status      0
skills                     0
excel_skill                0
sql_skill                  0
python_skill               0
power_bi_skill             0
looker_studio_skill        0
database_skill             0
tableau_skill              0
other_skills             637
candidate_goals            0
platform_source            0
province                   0
for_job                    0
upskills                   0
networking                 0
switch_career              0
dtype: int64

In [17]:
df.duplicated().sum()

0

In [18]:
len(df)

681

In [19]:
df.shape[1]

19

In [20]:
df["excel_skill"].sum()

527

In [21]:
df["fresh_graduate_status"].value_counts()

fresh_graduate_status
Ya       386
Tidak    295
Name: count, dtype: int64

In [22]:
df["province"].value_counts()

province
Jawa Barat             173
Jakarta                112
Jawa Timur              96
Jawa Tengah             70
Banten                  56
DI Yogyakarta           28
Sumatera Utara          19
Riau                    19
Sulawesi Selatan        14
Sumatera Barat          12
Kalimantan Selatan      11
Kalimantan Timur        11
Sumatera Selatan        10
Lampung                  8
Bengkulu                 6
Kalimantan Barat         6
Jambi                    5
Sulawesi Tenggara        4
Kalimantan Tengah        3
Belum ada mapping        3
Bangka  Belitung         3
Sulawesi Tengah          3
Nusa Tenggara Barat      3
Aceh                     2
Kalimatan Tengah         1
Bali                     1
Sumatra Selatan          1
Nusa Tenggara Timur      1
Name: count, dtype: int64